---
- hosts: localhost
  environment:
    AWS_PROFILE: frontend
    ANSIBLE_HOST_KEY_CHECKING: False
  tasks:
        
    - name: preinstall nvm
      shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash
    
    - name: nvm install correct version
      shell: . ~/.nvm/nvm.sh; nvm install
      args:
        chdir: ~/workspace/dotcom-rendering
        executable: /bin/bash
    
    - name: run make dev
      command: screen -S trousers-build -d -m make dev
      args:
        chdir: ~/workspace/dotcom-rendering
        
    - name: wait for the application to become available
      wait_for:
        port: 9000
        delay: 7
    
    - name: check that localhost is returning 200
      uri:
        url: http://localhost:9000/Article
