name: ðŸ§ª AB testing

permissions:
  contents: read

on:
  pull_request:
    paths:
      - 'ab-testing/**'
      - '.github/workflows/ab-testing-*.yml'
  push:
    branches:
      - main
    paths:
      - 'ab-testing/**'
      - '.github/workflows/ab-testing-*.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    defaults:
      run:
        working-directory: ab-testing
    env:
      FASTLY_AB_TESTING_CONFIG: ${{ secrets.FASTLY_AB_TESTING_CONFIG }}
      FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Node environment
        uses: ./.github/actions/setup-node-env

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint

      - name: Prettier Check
        run: pnpm prettier:check

      - name: Typecheck
        run: pnpm tsc

      - name: Validate
        run: pnpm validate

      - name: Build
        run: pnpm build

      - uses: actions/upload-artifact@v5
        with:
          name: ab-testing-build
          path: ab-testing/dist

  build-lambda:
    name: Build Lambda
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ab-testing/dictionary-deploy-lambda
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node environment
        uses: ./.github/actions/setup-node-env

      - name: Build Lambda
        run: pnpm build

      - name: Save build
        uses: actions/upload-artifact@v5
        with:
          name: ab-testing-lambda-build
          path: ab-testing/dictionary-deploy-lambda/dist

  build-ui:
    name: UI build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ab-testing/frontend
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node environment
        uses: ./.github/actions/setup-node-env

      - name: Build UI
        run: pnpm build

      - name: Save build
        uses: actions/upload-artifact@v5
        with:
          name: ui-build
          path: ab-testing/frontend/output/ab-tests.html
          if-no-files-found: error

  riff-raff:
    runs-on: ubuntu-latest
    needs: [build, build-ui, build-lambda]
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: ab-testing

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node
        uses: ./.github/actions/setup-node-env

      - name: Fetch build
        uses: actions/download-artifact@v6.0.0
        with:
          name: ab-testing-build

      - name: Fetch UI build
        uses: actions/download-artifact@v6.0.0
        with:
          name: ui-build
          path: ab-testing/frontend/output/ab-tests.html

      - name: Fetch Lambda build
        uses: actions/download-artifact@v6.0.0
        with:
          name: ab-testing-lambda-build
          path: ab-testing/dictionary-deploy-lambda/dist

      - name: CDK Test
        run: pnpm cdk:test

      - name: CDK synth
        run: pnpm cdk:synth

      - name: Riff-Raff Upload
        uses: guardian/actions-riff-raff@v4.1.9
        with:
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: dotcom:ab-testing
          configPath: ab-testing/cdk.out/riff-raff.yaml
          contentDirectories: |
            ab-testing:
              - ab-testing/dist
            ab-testing-dictionary-deploy-lambda:
              - ab-testing/dictionary-deploy-lambda/dist
            admin/ab-testing:
              - ab-testing/frontend/output/ab-tests.html
            cdk.out:
              - ab-testing/cdk.out
