name: AR Chromatic ðŸ‘“

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, labeled, synchronize, ready_for_review]

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    # Don't run Chromatic on draft PRs unless `run_chromatic` label has been applied.
    if: (contains(github.event.pull_request.labels.*.name, 'run_chromatic') || github.event.pull_request.draft == false)
    steps:
      - name: Checkout - On Pull Request
        uses: actions/checkout@v4
        if: ${{ github.event_name == 'pull_request'}}
        with:
          fetch-depth: 0
          # By default the pull_request event will run on a ephermeral merge commit which simulates a merge between the pull request
          # and the target branch. This can cause issues with Chromatic https://www.chromatic.com/docs/turbosnap#github-pullrequest-triggers
          # Hopefully by checking out the HEAD commit of a PR instead of the merge commit we can avoid some of those issues.
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout - On Push Event
        uses: actions/checkout@v4
        if: ${{ github.event_name == 'push'}}
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      # Root yarn installs all workspaces (root, dotcom)
      - run: yarn install --frozen-lockfile

      - name: Chromatic - Apps Rendering
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        uses: chromaui/action@v1

        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN__APPS_RENDERING }}
          token: ${{ secrets.GITHUB_TOKEN }}
          untraced: '**/(package*.json|yarn.lock|preview.js)'
          exitOnceUploaded: true
          onlyChanged: '!(main)' # only turbosnap on non-main branches
          workingDir: apps-rendering
