name: DCR Compressed Size
on:
  pull_request:
    paths-ignore:
      - "apps-rendering/**"
      - "dotcom-rendering/docs/**"

jobs:
  compressed_size:
    name: DCR Compressed Size
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: guardian/actions-setup-node@main

      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          build-script: build:dcr

          # https://github.com/preactjs/compressed-size-action#increasing-the-required-threshold
          minimum-change-threshold: 100

          # https://github.com/preactjs/compressed-size-action#dealing-with-hashed-filenames
          # The default hash digest is set to 20 chars in Webpack
          strip-hash: "\\.(\\w{20})\\.js$"
