name: Compressed Size

on: [pull_request]

jobs:
    compressed_size:
        name: Compressed Size
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: guardian/actions-setup-node@main
            - uses: preactjs/compressed-size-action@v1
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  build-script: makeBuild
