on:
  workflow_call:
    outputs:
      container-image:
        description: 'The generated container image path'
        value: ${{ jobs.image.outputs.container-image }}

jobs:
  image:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    outputs:
      container-image: ${{ steps.push.outputs.registry-path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.4.1

      - name: Set up Node environment
        uses: ./.github/actions/setup-node-env

      - name: Add commit hash for PRout
        working-directory: dotcom-rendering
        run: |
          echo 'export const GIT_COMMIT_HASH = "${{ github.sha }}";' > src/server/prout.ts

      - name: Generate production bundle
        run: make riffraff-bundle
        working-directory: dotcom-rendering

      - name: Build Container Image
        id: build_image
        uses: redhat-actions/buildah-build@v2.12
        with:
          image: dotcom-rendering
          tags: ${{ github.sha }} ${{ env.GITHUB_REF_SLUG }}
          context: ./
          containerfiles: ./dotcom-rendering/Containerfile

      - name: Push Image To GHCR
        uses: redhat-actions/push-to-registry@v2.7
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/guardian
          username: ${{ github.actor }}
          password: ${{ github.token }}
