name: Ngrok it
on: [push]
jobs:
    lhci:
        name: Ngrok it
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1
            - name: Use Node.js 10.15.3
              uses: actions/setup-node@v1
              with:
                  node-version: 10.15.3
            - run: make build
            - name: Ngrok it
              run: |
                  npm install -g ngrok
                  NODE_ENV=production node dist/frontend.server.js & ngrok http 9000 -log=stdout
                  sleep 180
                  

