on:
  workflow_call:
    inputs:
      container-image:
        description: 'Image used by DCR service'
        required: true
        type: string
    secrets:
      GU_RIFF_RAFF_ROLE_ARN:
        required: true

permissions:
  # Allow GitHub to request an OIDC JWT ID token, and to comment on pull requests as required by guardian/actions-riff-raff
  id-token: write
  pull-requests: write
jobs:
  riffraff:
    runs-on: ubuntu-latest

    steps:
      # Annoyingly we can't _easily_ access an Images filesystem without creating a container from the image.
      # we don't necessarily have to start the container, but we do need to create it.
      - name: Create DCR Container
        id: create-container
        run: echo "CONTAINER_ID=$(docker create ${{ inputs.container-image }})" >> "$GITHUB_OUTPUT"
      - name: Move container files into GHA Workspace
        run: docker cp ${{ steps.create-container.outputs.CONTAINER_ID }}:/opt/app/dotcom-rendering/dotcom-rendering/. ${{ github.workspace }}

      # We want to avoid uploading the uncompressed files to our riffraff bucket
      # so we create our tarball outside the folder, then delete the contents of
      # the folder, and finally move the tarball into the folder.
      - name: Compress article-rendering app server files
        run: |
          tar -zcf article-rendering.tar.gz article-rendering
          rm -r article-rendering/*
          mv article-rendering.tar.gz article-rendering/

      - name: Compress facia-rendering app server files
        run: |
          tar -zcf facia-rendering.tar.gz facia-rendering
          rm -r facia-rendering/*
          mv facia-rendering.tar.gz facia-rendering/

      - name: Compress tag-page-rendering app server files
        run: |
          tar -zcf tag-page-rendering.tar.gz tag-page-rendering
          rm -r tag-page-rendering/*
          mv tag-page-rendering.tar.gz tag-page-rendering/

      - name: Compress interactive-rendering app server files
        run: |
          tar -zcf interactive-rendering.tar.gz interactive-rendering
          rm -r interactive-rendering/*
          mv interactive-rendering.tar.gz interactive-rendering/

      # All rendering apps deployment
      - name: Upload rendering apps to RiffRaff
        uses: guardian/actions-riff-raff@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          projectName: dotcom:rendering-all
          configPath: riff-raff.yaml
          contentDirectories: |
            article-rendering-cfn:
              - article-rendering-cfn
            article-rendering:
              - article-rendering
            facia-rendering-cfn:
              - facia-rendering-cfn
            facia-rendering:
              - facia-rendering
            tag-page-rendering-cfn:
              - tag-page-rendering-cfn
            tag-page-rendering:
              - tag-page-rendering
            interactive-rendering-cfn:
              - interactive-rendering-cfn
            interactive-rendering:
              - interactive-rendering
            frontend-static:
              - frontend-static
